### ISSUE TITLE
Placeholderapi support

### ISSUE THREAD

**Issue by florensm** [Mi10tsuhashi/SimpleHide#1]
Hey there! This may seem dumb because this plugin hasnt been updated in 2 years and you're probably not planning to.

But is there any possibility that you could add placeholderapi support? Ive been looking all around spigotmc and cant find a simple plugin with just placeholderapi support so i can check if a placeholder is true or false, so i can add it in my menu.

Would be great if you are willing to add this.

Have a good day!

**Comment by Mi10tsuhashi** [comment]
Are you envisioning an implementation that gets a list of currently hidden players on the server via the PlaceHolder API?
For example,% SimpleHide_hidden% gets a list of players currently using the hide command.

**Comment by Mi10tsuhashi** [comment]
Added support for Placeholder API. Please let me know if it is different from what you think.
[https://github.com/Mi10tsuhashi/SimpleHide/commit/ae9c393aeff0e138b8d53ce889f0a8fb7119b899](https://github.com/Mi10tsuhashi/SimpleHide/commit/ae9c393aeff0e138b8d53ce889f0a8fb7119b899)
[https://www.spigotmc.org/resources/simplehide-1-12-x-1-13-x.65141/](https://www.spigotmc.org/resources/simplehide-1-12-x-1-13-x.65141)

**Comment by florensm** [comment]
Thanks! Will try it when i have the time!
